// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import assert from 'node:assert'
import { test } from 'vitest'
import { x } from './main'

test('accepting emails', () => {
  const html5EmailRegex =
    /^[\w.!#$%&'*+/=?^`{|}~-]+@[a-z\d](?:[a-z\d-]{0,61}[a-z\d])?(?:\.[a-z\d](?:[a-z\d-]{0,61}[a-z\d])?)*$/i
  const schema = x.string
    .size({ min: 1, max: 12 })
    .pattern(html5EmailRegex)
    .map((v) => v as string & { type: 'Email' })
  assert(schema.parse('test@toto').success === true)
  assert(schema.parse('ab3').success === false)
})

test('accepting uuids', () => {
  // source: https://regex101.com/r/FSfqWZ/1
  const uuidRegex =
    /[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}/gm

  const schema = x.string
    .pattern(uuidRegex)
    .map((v) => v as string & { type: 'UUID' })
  assert(schema.parse(crypto.randomUUID()).success === true)
  assert(schema.parse('ab3').success === false)
})
